logging:
  level:
    root: info
server:
  port: 8082
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
  cloud:
    subscribed-services: service-provider

spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
