logging:
  level:
    root: info
server:
  port: 8082
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
